# Generated by Django 3.1.5 on 2022-08-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namePass', models.CharField(max_length=150, verbose_name='Name of the Pass')),
                ('daysOfUse', models.IntegerField(default=0, verbose_name='Days of use')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
    ]
