# Generated by Django 3.1.5 on 2022-08-19 22:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientHistoryPasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateStart', models.DateField(default=datetime.date.today, verbose_name='Date Start')),
                ('dateEnd', models.DateField(verbose_name='Date End')),
                ('passID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.passes', verbose_name='Pass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
