# Generated by Django 3.1.5 on 2022-08-01 14:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=30, verbose_name='nameUser')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='typeUser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.usertype'),
            preserve_default=False,
        ),
    ]
