# Generated by Django 3.1.5 on 2022-08-01 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220801_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='typeUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.usertype'),
        ),
    ]
