# Generated by Django 3.1.5 on 2022-08-03 14:13

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220802_1740'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='typeUser',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'Client'), (2, 'Administrator'), (3, 'Cashier'), (4, 'Customer service'), (5, '')], default=1, max_length=1),
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
