# Generated by Django 3.1.5 on 2022-08-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220803_1613'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(1, 'Client'), (2, 'Administrator'), (3, 'Cashier'), (4, 'Customer service'), (5, 'Accountant'), (6, 'Press spokesman'), (7, 'Management')], default=1, max_length=1),
        ),
    ]
