# Generated by Django 3.1.5 on 2022-08-07 13:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('shortText', models.CharField(max_length=300, verbose_name='Short Text')),
                ('text', models.TextField(verbose_name='Text Content')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Created')),
                ('liked', models.IntegerField(default=0, verbose_name='Liked')),
                ('photo', models.FileField(upload_to='blogPhoto/', verbose_name='Photo')),
                ('photoAlt', models.CharField(max_length=100, verbose_name='Photo Alt')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
        ),
    ]
