# Generated by Django 3.1.5 on 2022-08-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogposts',
            name='shortText',
        ),
    ]
